# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stefonzo/Programs/Octopus-tracker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stefonzo/Programs/Octopus-tracker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefonzo/Programs/Octopus-tracker/CMakeFiles /home/stefonzo/Programs/Octopus-tracker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefonzo/Programs/Octopus-tracker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named octopus

# Build rule for target.
octopus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 octopus
.PHONY : octopus

# fast build rule for target.
octopus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/build
.PHONY : octopus/fast

src/headers/audioworks.o: src/headers/audioworks.cpp.o
.PHONY : src/headers/audioworks.o

# target to build an object file
src/headers/audioworks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/audioworks.cpp.o
.PHONY : src/headers/audioworks.cpp.o

src/headers/audioworks.i: src/headers/audioworks.cpp.i
.PHONY : src/headers/audioworks.i

# target to preprocess a source file
src/headers/audioworks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/audioworks.cpp.i
.PHONY : src/headers/audioworks.cpp.i

src/headers/audioworks.s: src/headers/audioworks.cpp.s
.PHONY : src/headers/audioworks.s

# target to generate assembly for a file
src/headers/audioworks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/audioworks.cpp.s
.PHONY : src/headers/audioworks.cpp.s

src/headers/disk_op.o: src/headers/disk_op.cpp.o
.PHONY : src/headers/disk_op.o

# target to build an object file
src/headers/disk_op.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/disk_op.cpp.o
.PHONY : src/headers/disk_op.cpp.o

src/headers/disk_op.i: src/headers/disk_op.cpp.i
.PHONY : src/headers/disk_op.i

# target to preprocess a source file
src/headers/disk_op.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/disk_op.cpp.i
.PHONY : src/headers/disk_op.cpp.i

src/headers/disk_op.s: src/headers/disk_op.cpp.s
.PHONY : src/headers/disk_op.s

# target to generate assembly for a file
src/headers/disk_op.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/disk_op.cpp.s
.PHONY : src/headers/disk_op.cpp.s

src/headers/help.o: src/headers/help.cpp.o
.PHONY : src/headers/help.o

# target to build an object file
src/headers/help.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/help.cpp.o
.PHONY : src/headers/help.cpp.o

src/headers/help.i: src/headers/help.cpp.i
.PHONY : src/headers/help.i

# target to preprocess a source file
src/headers/help.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/help.cpp.i
.PHONY : src/headers/help.cpp.i

src/headers/help.s: src/headers/help.cpp.s
.PHONY : src/headers/help.s

# target to generate assembly for a file
src/headers/help.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/help.cpp.s
.PHONY : src/headers/help.cpp.s

src/headers/instrument_properties.o: src/headers/instrument_properties.cpp.o
.PHONY : src/headers/instrument_properties.o

# target to build an object file
src/headers/instrument_properties.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/instrument_properties.cpp.o
.PHONY : src/headers/instrument_properties.cpp.o

src/headers/instrument_properties.i: src/headers/instrument_properties.cpp.i
.PHONY : src/headers/instrument_properties.i

# target to preprocess a source file
src/headers/instrument_properties.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/instrument_properties.cpp.i
.PHONY : src/headers/instrument_properties.cpp.i

src/headers/instrument_properties.s: src/headers/instrument_properties.cpp.s
.PHONY : src/headers/instrument_properties.s

# target to generate assembly for a file
src/headers/instrument_properties.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/instrument_properties.cpp.s
.PHONY : src/headers/instrument_properties.cpp.s

src/headers/moduleformat.o: src/headers/moduleformat.cpp.o
.PHONY : src/headers/moduleformat.o

# target to build an object file
src/headers/moduleformat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/moduleformat.cpp.o
.PHONY : src/headers/moduleformat.cpp.o

src/headers/moduleformat.i: src/headers/moduleformat.cpp.i
.PHONY : src/headers/moduleformat.i

# target to preprocess a source file
src/headers/moduleformat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/moduleformat.cpp.i
.PHONY : src/headers/moduleformat.cpp.i

src/headers/moduleformat.s: src/headers/moduleformat.cpp.s
.PHONY : src/headers/moduleformat.s

# target to generate assembly for a file
src/headers/moduleformat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/moduleformat.cpp.s
.PHONY : src/headers/moduleformat.cpp.s

src/headers/sample_edit.o: src/headers/sample_edit.cpp.o
.PHONY : src/headers/sample_edit.o

# target to build an object file
src/headers/sample_edit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sample_edit.cpp.o
.PHONY : src/headers/sample_edit.cpp.o

src/headers/sample_edit.i: src/headers/sample_edit.cpp.i
.PHONY : src/headers/sample_edit.i

# target to preprocess a source file
src/headers/sample_edit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sample_edit.cpp.i
.PHONY : src/headers/sample_edit.cpp.i

src/headers/sample_edit.s: src/headers/sample_edit.cpp.s
.PHONY : src/headers/sample_edit.s

# target to generate assembly for a file
src/headers/sample_edit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sample_edit.cpp.s
.PHONY : src/headers/sample_edit.cpp.s

src/headers/sdl_keymap.o: src/headers/sdl_keymap.cpp.o
.PHONY : src/headers/sdl_keymap.o

# target to build an object file
src/headers/sdl_keymap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sdl_keymap.cpp.o
.PHONY : src/headers/sdl_keymap.cpp.o

src/headers/sdl_keymap.i: src/headers/sdl_keymap.cpp.i
.PHONY : src/headers/sdl_keymap.i

# target to preprocess a source file
src/headers/sdl_keymap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sdl_keymap.cpp.i
.PHONY : src/headers/sdl_keymap.cpp.i

src/headers/sdl_keymap.s: src/headers/sdl_keymap.cpp.s
.PHONY : src/headers/sdl_keymap.s

# target to generate assembly for a file
src/headers/sdl_keymap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sdl_keymap.cpp.s
.PHONY : src/headers/sdl_keymap.cpp.s

src/headers/sequence_list.o: src/headers/sequence_list.cpp.o
.PHONY : src/headers/sequence_list.o

# target to build an object file
src/headers/sequence_list.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sequence_list.cpp.o
.PHONY : src/headers/sequence_list.cpp.o

src/headers/sequence_list.i: src/headers/sequence_list.cpp.i
.PHONY : src/headers/sequence_list.i

# target to preprocess a source file
src/headers/sequence_list.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sequence_list.cpp.i
.PHONY : src/headers/sequence_list.cpp.i

src/headers/sequence_list.s: src/headers/sequence_list.cpp.s
.PHONY : src/headers/sequence_list.s

# target to generate assembly for a file
src/headers/sequence_list.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/sequence_list.cpp.s
.PHONY : src/headers/sequence_list.cpp.s

src/headers/tracker.o: src/headers/tracker.cpp.o
.PHONY : src/headers/tracker.o

# target to build an object file
src/headers/tracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/tracker.cpp.o
.PHONY : src/headers/tracker.cpp.o

src/headers/tracker.i: src/headers/tracker.cpp.i
.PHONY : src/headers/tracker.i

# target to preprocess a source file
src/headers/tracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/tracker.cpp.i
.PHONY : src/headers/tracker.cpp.i

src/headers/tracker.s: src/headers/tracker.cpp.s
.PHONY : src/headers/tracker.s

# target to generate assembly for a file
src/headers/tracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/tracker.cpp.s
.PHONY : src/headers/tracker.cpp.s

src/headers/util.o: src/headers/util.cpp.o
.PHONY : src/headers/util.o

# target to build an object file
src/headers/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/util.cpp.o
.PHONY : src/headers/util.cpp.o

src/headers/util.i: src/headers/util.cpp.i
.PHONY : src/headers/util.i

# target to preprocess a source file
src/headers/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/util.cpp.i
.PHONY : src/headers/util.cpp.i

src/headers/util.s: src/headers/util.cpp.s
.PHONY : src/headers/util.s

# target to generate assembly for a file
src/headers/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/headers/util.cpp.s
.PHONY : src/headers/util.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/octopus.dir/build.make CMakeFiles/octopus.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... octopus"
	@echo "... src/headers/audioworks.o"
	@echo "... src/headers/audioworks.i"
	@echo "... src/headers/audioworks.s"
	@echo "... src/headers/disk_op.o"
	@echo "... src/headers/disk_op.i"
	@echo "... src/headers/disk_op.s"
	@echo "... src/headers/help.o"
	@echo "... src/headers/help.i"
	@echo "... src/headers/help.s"
	@echo "... src/headers/instrument_properties.o"
	@echo "... src/headers/instrument_properties.i"
	@echo "... src/headers/instrument_properties.s"
	@echo "... src/headers/moduleformat.o"
	@echo "... src/headers/moduleformat.i"
	@echo "... src/headers/moduleformat.s"
	@echo "... src/headers/sample_edit.o"
	@echo "... src/headers/sample_edit.i"
	@echo "... src/headers/sample_edit.s"
	@echo "... src/headers/sdl_keymap.o"
	@echo "... src/headers/sdl_keymap.i"
	@echo "... src/headers/sdl_keymap.s"
	@echo "... src/headers/sequence_list.o"
	@echo "... src/headers/sequence_list.i"
	@echo "... src/headers/sequence_list.s"
	@echo "... src/headers/tracker.o"
	@echo "... src/headers/tracker.i"
	@echo "... src/headers/tracker.s"
	@echo "... src/headers/util.o"
	@echo "... src/headers/util.i"
	@echo "... src/headers/util.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

